name: Setting up Github Actions
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  generate-changelog:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - env:
          MESSAGE: ${{ github.event.pull_request.title }}
        run: echo "$MESSAGE"
