name: Setting up Github Actions
on:
  push:
    branches:
      - main
      - develop

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          curl \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/1swaraj/GoJSON/pulls/${PR_NUMBER}/commits
