name: Setting up Github Actions
on:
  pull_request:
    branches:
      - main
      - master
      - stagging
    types:
      - closed

jobs:
  generate-changelog:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: 1swaraj/auto-generate-changelog@master
        env:
          PR_NUMBER: ${{ github.event.number }}
          TITLE: ${{ github.event.pull_request.title }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: Community Updates Ropsten
          DISCORD_AVATAR: https://pbs.twimg.com/profile_images/1315664565917581312/9da1QkqP.png
          TO: ${{ secrets.TELEGRAM_TO }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        with:
          REPO_NAME: ${{ github.repository }}
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
