name: Setting up Github Actions
on:
  push:
    branches:
      - main
      - develop

jobs:
  notification:
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(github.event)}}
    steps:
      - name: Echo Event
        run: |
          echo ${{ matrix.commits }}
