name: Setting up Github Actions
on:
  push:
    branches:
      - main
      - develop

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Event
        run: |
          for commit in ${{github.event.commits}}; do echo commit.message; done
