name: Setting up Github Actions
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  generate-changelog:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_EVENT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_EVENT"
      - env:
          MESSAGE: ${{ github.event.pull_request.title }}
        run: echo "$MESSAGE"
