name: Setting up Github Actions
on:
  push:
    branches:
      - main

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.3.0
        with:
          github-token: ${{github.token}}
          script: |
            const core = require('@actions/core')
            const prNumber = context.payload.number;
            core.exportVariable('PULL_NUMBER', prNumber);
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: 1swaraj/auto-generate-changelog@master
        with:
          REPO_NAME: "1swaraj/GoJSON"
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULLNUMBER: $PULL_NUMBER
