name: Setting up Github Actions
on:
  push:
    branches:
      - main
      - stagging

jobs:
  generate-changelog:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: echo "**Changes arrived :- ** *${{ github.event.head_commit.message }}*"
