name: Setting up Github Actions
on:
  push:
    branches:
      - main
      - develop

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
      - name: Echo Changelog
        run: |
          echo "${{ steps.changelog.outputs.clean_changelog }}"
