name: Setting up Github Actions
on:
  push:
    branches:
      - main
      - develop

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: 1swaraj/auto-generate-changelog@master
        with:
          REPO_NAME: "1swaraj/GoJSON"
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULLNUMBER: $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
